# Generated by Django 2.2.4 on 2019-09-16 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='number',
            name='num',
            field=models.PositiveIntegerField(),
        ),
    ]
